DECLARE
  v_start  TIMESTAMP;
  v_end    TIMESTAMP;
  v_diff   INTERVAL DAY TO SECOND;
BEGIN
  v_start := SYSTIMESTAMP;

  -- Your query here
  INSERT INTO STRESSLEVEL (
    ID, ANXIETY_LEVEL, SELF_ESTEEM, MENTAL_HEALTH_HISTORY, DEPRESSION,
    HEADACHE, BLOOD_PRESSURE, SLEEP_QUALITY, BREATHING_PROBLEM,
    NOISE_LEVEL, LIVING_CONDITIONS, SAFETY, BASIC_NEEDS, ACADEMIC_PERFORMANCE,
    STUDY_LOAD, TEACHER_STUDENT_RELATIONSHIP, FUTURE_CAREER_CONCERNS,
    SOCIAL_SUPPORT, PEER_PRESSURE, EXTRACURRICULAR_ACTIVITIES, BULLYING, STRESS_LEVEL
  )
  VALUES (
    2, 10, 14, 1, 1,
    2, 125, 3, 0,
    3, 2, 3, 1, 75,
    5, 3, 2,
    4, 3, 1, 0, 4
  );

  v_end := SYSTIMESTAMP;
  v_diff := v_end - v_start;

  DBMS_OUTPUT.PUT_LINE('Execution time: ' || v_diff);
END;
