DECLARE
  v_start TIMESTAMP;
  v_end   TIMESTAMP;
  v_diff  INTERVAL DAY TO SECOND;
BEGIN
  v_start := SYSTIMESTAMP;

  INSERT INTO STRESSLEVEL (
    ID, ANXIETY_LEVEL, SELF_ESTEEM, MENTAL_HEALTH_HISTORY, DEPRESSION,
    HEADACHE, BLOOD_PRESSURE, SLEEP_QUALITY, BREATHING_PROBLEM,
    NOISE_LEVEL, LIVING_CONDITIONS, SAFETY, BASIC_NEEDS, ACADEMIC_PERFORMANCE,
    STUDY_LOAD, TEACHER_STUDENT_RELATIONSHIP, FUTURE_CAREER_CONCERNS,
    SOCIAL_SUPPORT, PEER_PRESSURE, EXTRACURRICULAR_ACTIVITIES, BULLYING, STRESS_LEVEL
  ) VALUES (
    10001, 10, 14, 1, 1,
    3, 125, 3, 0,
    2, 2, 3, 1, 80,
    5, 3, 2,
    4, 4, 1, 0, 3
  );

  v_end := SYSTIMESTAMP;
  v_diff := v_end - v_start;
  DBMS_OUTPUT.PUT_LINE('Insert time: ' || v_diff);
END;
