BEGIN
  FOR i IN 1..59 LOOP
    INSERT INTO STRESSLEVEL (
      ID, ANXIETY_LEVEL, SELF_ESTEEM, MENTAL_HEALTH_HISTORY, DEPRESSION,
      HEADACHE, BLOOD_PRESSURE, SLEEP_QUALITY, BREATHING_PROBLEM,
      NOISE_LEVEL, LIVING_CONDITIONS, SAFETY, BASIC_NEEDS, ACADEMIC_PERFORMANCE,
      STUDY_LOAD, TEACHER_STUDENT_RELATIONSHIP, FUTURE_CAREER_CONCERNS,
      SOCIAL_SUPPORT, PEER_PRESSURE, EXTRACURRICULAR_ACTIVITIES, BULLYING, STRESS_LEVEL
    )
    SELECT 
      ID + i * 1000 + 500001, ANXIETY_LEVEL, SELF_ESTEEM, MENTAL_HEALTH_HISTORY, DEPRESSION,
      HEADACHE, BLOOD_PRESSURE, SLEEP_QUALITY, BREATHING_PROBLEM,
      NOISE_LEVEL, LIVING_CONDITIONS, SAFETY, BASIC_NEEDS, ACADEMIC_PERFORMANCE,
      STUDY_LOAD, TEACHER_STUDENT_RELATIONSHIP, FUTURE_CAREER_CONCERNS,
      SOCIAL_SUPPORT, PEER_PRESSURE, EXTRACURRICULAR_ACTIVITIES, BULLYING, STRESS_LEVEL
    FROM STRESSLEVEL
    WHERE ID <= 1000;
  END LOOP;
END;
